builds:
  # List of builds
  - # First Build
    env:
    - CGO_ENABLED=0
    main: main.go
    ldflags: '-s -w -X github.com/sensu/sensu-plugin-sdk/version.version={{.Version}} -X github.com/sensu/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/{{ .ProjectName }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
