builds:
  # List of builds
  - # First Build
    env:
    - CGO_ENABLED=0
    main: main.go
    ldflags: >
      -w -s
      -X github.com/prometheus/common/version.Version={{ .Version }}
      -X github.com/prometheus/common/version.Revision={{ .Commit }}
      -X github.com/prometheus/common/version.Branch={{ .Branch }}
      -X github.com/prometheus/common/version.BuildUser=reproducible
      -X github.com/prometheus/common/version.BuildDate={{ .Date }}
    binary: bin/{{ .ProjectName }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
